services:
    mailer.message_logger_listener:
        class: Symfony\Component\Mailer\EventListener\MessageLoggerListener
        arguments:
            - null
        public: true
        tags:
            - { name: kernel.event_subscriber }
            - { name: kernel.reset, method: reset }
